# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: nginx-rs
#   labels:
#     env: demo
# spec:
#   replicas: 4
#   selector:
#     matchLabels:
#       env: demo
#   template:
#     metadata:
#       labels:
#         env: demo
#     spec:
#       containers:
#       - name: nginx-pod
#         image: nginx


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   labels:
#     tier: backend
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: v1
#   template:
#     metadata:
#       labels:
#         app: v1
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.23.0
#         ports:
#         - containerPort: 80


# apiVersion: apps/v1
# kind:  Deployment
# metadata:
#   name: nginx-deploy
#   labels:
#     env: demo
# spec:
#   template:
#     metadata:
#       labels:
#         env: demo
#         name: nginx
#     spec:
#       containers:
#       - image: nginx
#         name: nginx
#         ports:
#         - containerPort: 80
#   replicas: 3
#   selector:
#     matchLabels:
#       env: demo

apiVersion: apps/v1
kind:  Deployment
metadata:
  name: nginx-deploymet
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      env: demo