# apiVersion: v1
# kind: ReplicationController
# metadata:
#  name: nginx-rc
#  labels:
#   env: demo
# spec:
#   template:
#     metadata: 
#       name: nginx-pod
#       labels:
#         env: demo
#         type: frontend
#     spec:
#       containers:
#       - name: nginx-container
#         image: nginx
#   replicas: 3

# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#  name: nginx-rs
#  labels:
#   env: demo
# spec:
#   template:
#     metadata: 
#       name: nginx-pod
#       labels:
#         env: demo
#         type: frontend
#     spec:
#       containers:
#       - name: nginx-container
#         image: nginx
#   replicas: 3
#   selector:
#     matchLabels:
#       env: demo

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deploy
 labels:
  env: demo
spec:
  template:
    metadata: 
      name: nginx-pod
      labels:
        env: demo
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      env: demo