apiVersion: v1
kind: Pod
metadata:
  labels:
  name: agnhost
spec:
  containers:
  - image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: agnhost
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10