apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cj
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - echo 40daysofkubernetes
          restartPolicy: OnFailure          