# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp
# spec:
#   selector:
#     env: demo
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    env: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001