apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
  labels:
    env: prod
spec:
  nodeName: cka-cluster-worker2
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80